/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/learning-path/': RouteRecordInfo<
      '/learning-path/',
      '/learning-path',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/learning-path/arm-motion-control/': RouteRecordInfo<
      '/learning-path/arm-motion-control/',
      '/learning-path/arm-motion-control',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/learning-path/electrical-control/': RouteRecordInfo<
      '/learning-path/electrical-control/',
      '/learning-path/electrical-control',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/learning-path/electrical-control/1': RouteRecordInfo<
      '/learning-path/electrical-control/1',
      '/learning-path/electrical-control/1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/learning-path/electrical-control/2': RouteRecordInfo<
      '/learning-path/electrical-control/2',
      '/learning-path/electrical-control/2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/learning-path/electrical-control/3-1': RouteRecordInfo<
      '/learning-path/electrical-control/3-1',
      '/learning-path/electrical-control/3-1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/learning-path/electrical-control/3-2': RouteRecordInfo<
      '/learning-path/electrical-control/3-2',
      '/learning-path/electrical-control/3-2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/learning-path/electrical-control/3-3': RouteRecordInfo<
      '/learning-path/electrical-control/3-3',
      '/learning-path/electrical-control/3-3',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/learning-path/electrical-control/3-4': RouteRecordInfo<
      '/learning-path/electrical-control/3-4',
      '/learning-path/electrical-control/3-4',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/learning-path/electrical-control/3-5': RouteRecordInfo<
      '/learning-path/electrical-control/3-5',
      '/learning-path/electrical-control/3-5',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/learning-path/electrical-control/4-1': RouteRecordInfo<
      '/learning-path/electrical-control/4-1',
      '/learning-path/electrical-control/4-1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/learning-path/electrical-control/4-2': RouteRecordInfo<
      '/learning-path/electrical-control/4-2',
      '/learning-path/electrical-control/4-2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/learning-path/electrical-control/4-3': RouteRecordInfo<
      '/learning-path/electrical-control/4-3',
      '/learning-path/electrical-control/4-3',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/learning-path/electrical-control/4-4': RouteRecordInfo<
      '/learning-path/electrical-control/4-4',
      '/learning-path/electrical-control/4-4',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/learning-path/electrical-control/5': RouteRecordInfo<
      '/learning-path/electrical-control/5',
      '/learning-path/electrical-control/5',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/project/PiPER': RouteRecordInfo<
      '/posts/project/PiPER',
      '/posts/project/PiPER',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/project/Renesas': RouteRecordInfo<
      '/posts/project/Renesas',
      '/posts/project/Renesas',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-sakura@0.10.2__e04e6cbfae6fe749bc87e0239ee6324b/node_modules/valaxy-theme-sakura/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy@0.28.4_@babel+parser_6046c482f2cae9a8ea4fdf503856ded0/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
    }
    'pages/learning-path/index.md': {
      routes:
        | '/learning-path/'
      views:
        | never
    }
    'pages/learning-path/arm-motion-control/index.md': {
      routes:
        | '/learning-path/arm-motion-control/'
      views:
        | never
    }
    'pages/learning-path/electrical-control/index.md': {
      routes:
        | '/learning-path/electrical-control/'
      views:
        | never
    }
    'pages/learning-path/electrical-control/1.md': {
      routes:
        | '/learning-path/electrical-control/1'
      views:
        | never
    }
    'pages/learning-path/electrical-control/2.md': {
      routes:
        | '/learning-path/electrical-control/2'
      views:
        | never
    }
    'pages/learning-path/electrical-control/3-1.md': {
      routes:
        | '/learning-path/electrical-control/3-1'
      views:
        | never
    }
    'pages/learning-path/electrical-control/3-2.md': {
      routes:
        | '/learning-path/electrical-control/3-2'
      views:
        | never
    }
    'pages/learning-path/electrical-control/3-3.md': {
      routes:
        | '/learning-path/electrical-control/3-3'
      views:
        | never
    }
    'pages/learning-path/electrical-control/3-4.md': {
      routes:
        | '/learning-path/electrical-control/3-4'
      views:
        | never
    }
    'pages/learning-path/electrical-control/3-5.md': {
      routes:
        | '/learning-path/electrical-control/3-5'
      views:
        | never
    }
    'pages/learning-path/electrical-control/4-1.md': {
      routes:
        | '/learning-path/electrical-control/4-1'
      views:
        | never
    }
    'pages/learning-path/electrical-control/4-2.md': {
      routes:
        | '/learning-path/electrical-control/4-2'
      views:
        | never
    }
    'pages/learning-path/electrical-control/4-3.md': {
      routes:
        | '/learning-path/electrical-control/4-3'
      views:
        | never
    }
    'pages/learning-path/electrical-control/4-4.md': {
      routes:
        | '/learning-path/electrical-control/4-4'
      views:
        | never
    }
    'pages/learning-path/electrical-control/5.md': {
      routes:
        | '/learning-path/electrical-control/5'
      views:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-sakura@0.10.2__e04e6cbfae6fe749bc87e0239ee6324b/node_modules/valaxy-theme-sakura/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
    }
    'pages/posts/project/PiPER.md': {
      routes:
        | '/posts/project/PiPER'
      views:
        | never
    }
    'pages/posts/project/Renesas.md': {
      routes:
        | '/posts/project/Renesas'
      views:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
